//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knjiznica.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=192.168.1.8;uid=suky;pwd=0000;database=knjiznica;\r\n")]
        public string localConnection {
            get {
                return ((string)(this["localConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=donyslav.ddns.net;uid=suky;pwd=0000;database=knjiznica;")]
        public string remoteConneciton {
            get {
                return ((string)(this["remoteConneciton"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string databaseLocation {
            get {
                return ((string)(this["databaseLocation"]));
            }
            set {
                this["databaseLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://dony_mongo:MongoPw123@knjiznica-shard-00-00-kxqhb.mongodb.net:27017,knj" +
            "iznica-shard-00-01-kxqhb.mongodb.net:27017,knjiznica-shard-00-02-kxqhb.mongodb.n" +
            "et:27017/knjiznica?ssl=true&replicaSet=knjiznica-shard-0&authSource=admin")]
        public string mongoLocalConn {
            get {
                return ((string)(this["mongoLocalConn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb://dony_mongo:MongoPw123@knjiznica-shard-00-00-kxqhb.mongodb.net:27017,knj" +
            "iznica-shard-00-01-kxqhb.mongodb.net:27017,knjiznica-shard-00-02-kxqhb.mongodb.n" +
            "et:27017/knjiznica?ssl=true&replicaSet=knjiznica-shard-0&authSource=admin")]
        public string mongoRemoteConn {
            get {
                return ((string)(this["mongoRemoteConn"]));
            }
        }
    }
}
